// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs5xlYRCYVP03GcAuRBeHiFRJSFHHVPEc',
    appId: '1:973079374954:web:9d6d80f8b1f0f243516e13',
    messagingSenderId: '973079374954',
    projectId: 'quickey-fdc32',
    authDomain: 'quickey-fdc32.firebaseapp.com',
    storageBucket: 'quickey-fdc32.appspot.com',
    measurementId: 'G-GF0KF9BFT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMy3m_RuVMOEvgX-Wsrl_hMN_OE3CgesE',
    appId: '1:973079374954:android:798705a5e93ac5d4516e13',
    messagingSenderId: '973079374954',
    projectId: 'quickey-fdc32',
    storageBucket: 'quickey-fdc32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3owMhEGuhoIuVdM3mNvAuFEGgoIx4Bk8',
    appId: '1:973079374954:ios:4b8f04d36a6f594b516e13',
    messagingSenderId: '973079374954',
    projectId: 'quickey-fdc32',
    storageBucket: 'quickey-fdc32.appspot.com',
    androidClientId: '973079374954-6ua2cd4nt78lh1remh6s4g3q810j1v1u.apps.googleusercontent.com',
    iosClientId: '973079374954-gf6qgc0h1ei5ivp43ft3kl11ff9chbjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickeyFlutter',
  );
}

